Format code using scalafmt
moia-oss/teleproto pull request #175
Opened 2022-03-07 10:29 UTC by lxwbr

#### Has the version number been increased?
 - [ ] Yes! (or not but it was intended to not increase it)

2022-03-07 10:48 UTC, joroKr21 commented
Should we check it in CI?

2022-03-07 11:09 UTC, saeltz requested changes

2022-03-07 11:09 UTC, saeltz commented on src/main/scala/io/moia/protos/teleproto/ReaderImpl.scala
> +    * PbSuccess(ModelEnum.OPTION_N) case Unrecognized(other) => PbFailure(s"Enumeration value $other is unrecognized!") }
Same here.

2022-03-07 11:09 UTC, saeltz commented on src/main/scala/io/moia/protos/teleproto/WriterImpl.scala
> +    * protobuf.Bar](value.asInstanceOf[model.Bar])))
Should be in a code block.

2022-03-07 11:09 UTC, saeltz commented on src/main/scala/io/moia/protos/teleproto/WriterImpl.scala
> +    * (model: ModelEnum) => p match { case ModelEnum.OPTION_1 => ProtoEnum.OPTION_1 ... case ModelEnum.OPTION_N => ProtoEnum.OPTION_N }
Same here.

2022-04-11 12:53 UTC, saeltz commented
Superseded by #185.

2022-04-11 12:53 UTC, closed without merging